version: '3.3'
services:
  mongo:
    image: mongo:4.2.5
  app:
    build: .
    environment:
      REDIS_HOST: redis
      WAIT_HOSTS: mongo:27017
    ports:
      - '5000:5000'
    depends_on:
      - redis
  redis:
      image: redis